version: 2

models:
  - name: deliveries
    columns: 
      - name: index
        tests: 
          - not_null
          - unique 

  - name: reactions
    columns: 
      - name: index
        tests: 
          - not_null
          - unique 

  - name: sendings
    columns: 
      - name: index
        tests: 
          - not_null
          - unique 
